export const divider: string
export const layoutCenter: string
export const layout: string
export const layoutTop: string
export const fakeSpace: string
export const home: string
export const contenedor: string
export const fl1: string
export const fl2: string
export const btnHome: string
export const btnContribuir: string
export const btnColab: string
export const containerBanner: string
export const imgBannerI: string
export const imgBanner: string
export const contentBanner: string
export const content: string
export const text: string
export const btnBanner: string
export const btnFl: string
export const texto: string
export const desc: string
export const colm2: string
export const colm3: string
export const colm4: string
export const fuente: string
export const containerStats: string
export const resStats: string
export const result: string
export const resCov: string
export const valor: string
export const resultInfo: string
export const containerColabor: string
export const colaborar: string
export const containerInfoHome: string
export const infoHome: string
export const flexRev: string
export const containerInfo: string
export const linea: string
export const containerImgInfo: string
export const cont: string
export const formaIm: string
export const forma: string
export const svgF: string
export const img: string
export const containerAbout: string
export const about: string
export const containerImg: string
export const tit: string
export const containerOngs: string
export const containerFichas: string
export const i4: string
export const ficha: string
export const containerContribuir: string
