export const firstBlue: string
export const motion: string
export const secondBlue: string
export const thirdBlue: string
export const firstGreen: string
export const secondGreen: string
export const firstRed: string
export const secondRed: string
export const thirdRed: string
export const lineOne: string
export const lineTwo: string
export const lineThree: string
export const lineFour: string
export const lineFive: string
export const lifeFive: string
export const lineSix: string
export const lineSeven: string
export const liveSeven: string
export const final: string
export const gentemLogo: string
