export const admin: string
export const title: string
export const chooseEdit: string
export const createOrg: string
export const createOrgForm: string
export const createOrgLabel: string
export const btn: string
export const blue: string
export const createOrgModal: string
export const modalClose: string
