export const divider: string
export const footer: string
export const footerContact: string
export const antLayoutFooter: string
export const mailColor: string
export const socialMedia: string
export const socialMediaIcon: string
export const language: string
export const activate: string
export const circle: string
