export const divider: string
export const layoutCenter: string
export const layout: string
export const layoutTop: string
export const fixed: string
export const header: string
export const headerContent: string
export const headerLogo: string
export const headerBtn: string
export const headerBtnText: string
