export const divider: string
export const layoutCenter: string
export const layout: string
export const layoutTop: string
export const ongList: string
export const ongListContent: string
export const banner: string
export const bannerContent: string
export const ongListSearch: string
export const ongListSearchContainer: string
export const textCheck: string
export const textCheckTop: string
export const textCheckBottom: string
export const ongListResult: string
export const ongListResultQuantity: string
export const quantityBtn: string
export const ongListResultFilter: string
export const resultItem: string
export const resultItemImg: string
export const resultItemDetails: string
export const additionals: string
export const optionFilters: string
export const itemDetailsTitle: string
export const itemDetailsDesc: string
export const itemDetailsFooter: string
export const detailsFooterTarget: string
export const footerTargetPrincipal: string
export const target: string
export const targetSpan: string
export const detailsFooterLocation: string
export const targetMore: string
export const seeMoreContainer: string
export const seeMore: string
export const seeMoreText: string
export const noOrganization: string
export const noOrganizationBtnContainer: string
export const noOrganizationBtn: string
export const listModal: string
export const modalClose: string
export const ongListModal: string
export const ongListModalLogo: string
export const organizationGrid: string
export const ongLis: string
