export const divider: string
export const layoutCenter: string
export const layout: string
export const layoutTop: string
export const ongProfile: string
export const ongProfileContent: string
export const ongProfileHero: string
export const ongProfileUserImgBreadcrumb: string
export const ongProfileUserImg: string
export const ongProfileUserBreadcrumb: string
export const ongProfileUserInfo: string
export const ongProfileInfoTitle: string
export const ongProfileInfoDescription: string
export const ongProfileUserHowUseDonation: string
export const ongProfileUserSponsors: string
export const ongProfileObjectiveTitle: string
export const ongProfileHowUseDonationTitle: string
export const ongProfileSponsorsTitle: string
export const ongProfileContactTitle: string
export const ongProfileAddressTitle: string
export const ongProfileObjectiveDescription: string
export const ongProfileHowUseDonationDescription: string
export const ongProfileHowToDonateContact: string
export const ongProfileUserAddress: string
export const responsiveInfoActive: string
export const ongProfileSponsorsContainer: string
export const ongProfileContainerImg: string
export const ongProfileAddressInfo: string
export const ongProfileInfoIcon: string
export const ongProfileFixedHowToDonate: string
export const ongProfileFixedHowToDonateButton: string
export const ongProfileFixedHowToDonateMessageButton: string
export const ongProfileDivider: string
export const ongProfileHowToDonate: string
export const ongProfileTitleDivider: string
export const ongProfileUserModal: string
export const ongProfileDonateDonateWay: string
export const ongProfileHowToDonateDonateProduct: string
export const ongProfileContactInfo: string
export const ongProfileInfoTel: string
export const ongProfileSocial: string
export const ongProfileSocialNetworks: string
export const h4: string
export const span: string
export const map: string
export const mapInfo: string
export const marker: string
export const markerFill: string
export const markerFillFill: string
export const ongProfileModal: string
export const modalClose: string
export const ongProfileUserModalImg: string
export const ongProfileHowToDonateTitle: string
export const ongProfileUserModalTitle: string
export const howToDonateBank: string
export const ongProfileUserModalDonationProduct: string
export const ongProfileUserModalDonationPlace: string
export const ongProfileUserContact: string
export const ongProfileTarget: string
export const address: string
export const textContainer: string
export const textContainerCountry: string
