export const divider: string
export const layoutCenter: string
export const layout: string
export const layoutTop: string
export const reactModalPortal: string
export const nprogress: string
export const bar: string
export const peg: string
export const spinner: string
export const spinnerIcon: string
export const nprogressSpinner: string
export const nprogressCustomParent: string
export const beta: string
export const betaContainer: string
export const infoImg: string
export const betaText: string
export const betaBtn: string
