export const divider: string
export const layoutCenter: string
export const layout: string
export const layoutTop: string
export const button: string
export const dividerHorizontal: string
export const containerSelect: string
export const select: string
export const boxSelect: string
export const ReactModalContainer: string
export const ReactPortalCustom: string
export const ReactOverlay: string
export const modal: string
export const modalOpen: string
export const activeSelect: string
export const active: string
export const value: string
export const option: string
export const extend: string
