export const layout: string
export const infoContainer: string
export const image: string
export const textContainer: string
export const name: string
export const location: string
export const causeAndDonations: string
export const donation: string
export const filterTitle: string
export const spanContainer: string
export const filterSpan: string
export const link: string
export const filterContainer: string
